server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Last Words API logs
  - job_name: last-words-api
    static_configs:
      - targets:
          - localhost
        labels:
          job: last-words-api
          service: api
          __path__: /var/log/last-words/api/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: msg
            service: service
            userId: userId
            operation: operation
            requestId: requestId
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          service:
          operation:
      - output:
          source: message

  # Last Words Web logs
  - job_name: last-words-web
    static_configs:
      - targets:
          - localhost
        labels:
          job: last-words-web
          service: web
          __path__: /var/log/last-words/web/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: msg
            service: service
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          service:

  # Audit logs (special handling)
  - job_name: audit-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: audit-logs
          service: audit
          __path__: /var/log/last-words/audit/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            operation: operation
            resource: resource
            action: action
            result: result
            userId: userId
            sessionId: sessionId
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          operation:
          resource:
          action:
          result:
          level:

  # System logs
  - job_name: syslog
    static_configs:
      - targets:
          - localhost
        labels:
          job: syslog
          __path__: /var/log/syslog
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\S+\s+\d+\s+\d+:\d+:\d+)\s+(?P<hostname>\S+)\s+(?P<service>\S+):\s+(?P<message>.*)$'
      - timestamp:
          source: timestamp
          format: Jan 2 15:04:05
      - labels:
          hostname:
          service:

  # Docker container logs
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*.log
    pipeline_stages:
      - json:
          expressions:
            log: log
            stream: stream
            time: time
      - timestamp:
          source: time
          format: RFC3339Nano
      - labels:
          stream:
      - output:
          source: log
