global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@lastwords.app'
  smtp_auth_username: 'alerts@lastwords.app'
  smtp_auth_password: 'your-smtp-password'

route:
  group_by: ['alertname', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
    - match:
        service: security
      receiver: 'security-team'
    - match:
        service: audit
      receiver: 'compliance-team'

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://host.docker.internal:3001/api/alerts/webhook'
        send_resolved: true

  - name: 'critical-alerts'
    email_configs:
      - to: 'admin@lastwords.app'
        subject: 'CRITICAL: {{ .GroupLabels.alertname }} - Last Words'
        html: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Status: {{ .Status }}
          Labels: {{ range .Labels.SortedPairs }}{{ .Name }}={{ .Value }} {{ end }}
          {{ end }}
    webhook_configs:
      - url: 'http://host.docker.internal:3001/api/alerts/webhook'
        send_resolved: true

  - name: 'security-team'
    email_configs:
      - to: 'security@lastwords.app'
        subject: 'SECURITY ALERT: {{ .GroupLabels.alertname }} - Last Words'
        html: |
          SECURITY INCIDENT DETECTED
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Service: {{ .Labels.service }}
          Time: {{ .StartsAt }}
          
          Immediate investigation required.
          {{ end }}

  - name: 'compliance-team'
    email_configs:
      - to: 'compliance@lastwords.app'
        subject: 'AUDIT ALERT: {{ .GroupLabels.alertname }} - Last Words'
        html: |
          AUDIT SYSTEM ALERT
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Time: {{ .StartsAt }}
          
          Audit trail integrity may be compromised.
          {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'service']
